name: Build

# Trigger on every pull request and on push to the master
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  Build:
    runs-on: ubuntu-latest # run on a Linux machine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Make gradlew executable
        run: git update-index --chmod=+x gradlew
             git commit -m "Make gradlew executable"
      - name: Build the app
        run: ./gradlew build
